services:
  postgres:
    image: postgres:15
    env_file:
      - ./backend/.env  # Use backend .env for DB vars if present
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-yourpassword}
      POSTGRES_DB: ${POSTGRES_DB:-cve_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    mem_limit: 1g

  backend:
    build: ./backend
    volumes:
      - .:/app
    working_dir: /app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - postgres
      - redis
      - elasticsearch

  celery:
    build: ./backend
    command: celery -A backend.tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    working_dir: /app/backend
    env_file:
      - ./backend/.env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - backend
      - redis
      - postgres
      - elasticsearch

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  postgres-data:
  redis-data:
  es-data: