name: Backend Tests
on:
  push:
    paths:
      - backend/**
      - tests/**
      - .github/workflows/**
  pull_request:
    paths:
      - backend/**
      - tests/**
      - .github/workflows/**
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: yourpassword
          POSTGRES_DB: cve_test_db
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s
          --health-timeout=5s --health-retries=5
      redis:
        image: redis:6.2.0
        ports:
          - 6379:6379
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        env:
          discovery.type: single-node
          xpack.security.enabled: false
        ports:
          - 9200:9200
          - 9300:9300
        options: --health-cmd="curl -f http://localhost:9200/_cluster/health || exit 1"
          --health-interval=10s --health-timeout=5s --health-retries=10
    env:
      DATABASE_URL: postgresql://postgres:yourpassword@localhost:5432/cve_test_db
      REDIS_URL: redis://localhost:6379/0
      ELASTICSEARCH_URL: http://localhost:9200
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backend tests
        run: |
          cd backend
          pytest --maxfail=2 --disable-warnings -v
